name : my first workflow 
on : push 
jobs:
  first-job:
    runs-on : ubuntu-latest
    steps: 
    - name : checkout 
      uses: actions/checkout@v3

    - name : run multiple command over single run 
      run: |
        echo "hello avinash"
        ls
        cat README.md



    # - name : list file
    #   run : ls 
    # - name : read file 
    #   run : cat README.md
        
      

